service: alexa-slack-assistant
# app and org for use with dashboard.serverless.com
app: alexa-slack-assistant
org: psvoltaire96
custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-plugin-bespoken
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  hello:
    handler: src/handler.hello
#    Define function environment variables here
#    environment:
#      variable2: value2
