service: alexa-slack-assistant
# app and org for use with dashboard.serverless.com
app: alexa-slack-assistant
org: psvoltaire96
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  hello:
    handler: src/handler.hello
#    Define function environment variables here
#    environment:
#      variable2: value2
